# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='i.e. david', max_length=1000)),
                ('phone_number', models.IntegerField(default='i.e. 7651111111')),
                ('contact_email', models.TextField(default='i.e. david@purdue.edu', max_length=200)),
            ],
        ),
    ]
