# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_order_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_brand', models.CharField(help_text='i.e. Decodron', max_length=200)),
                ('drug_name', models.CharField(help_text='i.e. Amoxicillin', max_length=200)),
                ('strength', models.CharField(help_text='i.e. 500ml', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='already_pickup',
        ),
        migrations.RemoveField(
            model_name='order',
            name='doctor_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drug_brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drug_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ready_to_pickup',
        ),
        migrations.RemoveField(
            model_name='order',
            name='strength',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Products Ordered'), ('filled', 'Order Filled'), ('remove', 'Taken Out of Inventory'), ('ready', 'Order Ready for Pick Up'), ('billing', 'Order Delivered'), ('complete', 'Billing Complete')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(help_text='Any additional information', max_length=1000),
        ),
        migrations.AddField(
            model_name='drug',
            name='order_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Order'),
        ),
    ]
