# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20170219_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_strength', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wish_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_drug_name', models.CharField(max_length=200)),
                ('wish_drug_brand', models.CharField(max_length=200)),
                ('wish_drug_strength', models.CharField(max_length=50)),
                ('wish_drug_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(help_text='i.e. david', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.CharField(help_text='i.e. david@purdue.edu', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(help_text='i.e. 7651111111'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='drug',
            name='strength',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(default='If you have any comments, please add it here', max_length=1000),
        ),
        migrations.AddField(
            model_name='wish_list',
            name='client_obj_wish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
