# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20170326_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shopping', 'Put in Shopping Cart'), ('new', 'Products Ordered'), ('filled', 'Order Filled'), ('remove', 'Taken Out of Inventory'), ('ready', 'Order Ready for Pick Up'), ('billing', 'Order Delivered'), ('complete', 'Billing Complete')], default='new', max_length=50),
        ),
    ]
