# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0006_auto_20170328_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_drug_brand', models.CharField(max_length=200)),
                ('shopping_drug_name', models.CharField(max_length=200)),
                ('shopping_strength', models.CharField(max_length=50)),
                ('shopping_quantity', models.IntegerField(default=0)),
                ('client_obj_shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shopping', 'Put in Shopping Cart'), ('new', 'Products Ordered'), ('filled', 'Order Filled'), ('remove', 'Taken Out of Inventory'), ('ready', 'Order Ready for Pick Up'), ('billing', 'Order Delivered'), ('complete', 'Billing Complete')], default='shopping', max_length=50),
        ),
    ]
