# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20170330_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Products Ordered'), ('filled', 'Order Filled'), ('remove', 'Taken Out of Inventory'), ('ready', 'Order Ready for Pick Up'), ('billing', 'Order Delivered'), ('complete', 'Billing Complete')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='client_obj_shopping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
