# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('product_strength', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('CIN', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product_List',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='drug_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='drug_name',
            new_name='name',
        ),
    ]
