# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20170406_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_strength',
            new_name='strength',
        ),
    ]
