# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20170406_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, help_text='description here', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Vendor', 'Customer'), ('Administrator', 'Administrator')], default='Vendor', max_length=50),
        ),
    ]
