# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(default='i.e. Amoxicillin', max_length=1000)),
                ('drug_brand', models.CharField(default='i.e. Decodron', max_length=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('strength', models.CharField(default='i.e. 500ml', max_length=1000)),
                ('comment', models.TextField(default='Any additional information', max_length=1000)),
                ('ready_to_pickup', models.BooleanField(default=False)),
                ('already_pickup', models.BooleanField(default=False)),
                ('doctor_name', models.CharField(default='i.e. Paul1027', max_length=1000)),
                ('doctor_email', models.CharField(default='i.e. Paul1027@purdue.edu', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.CharField(default='i.e. david@purdue.edu', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='client_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
